### ISSUE TITLE
Integrating with Browserify

### ISSUE THREAD

**Issue by syfonseq** [Prezent/ractive-decorators-select2#8]
Hi,

What is the proper way to load the decorator using Browserify? I cannot achieve to get the decorator loaded, I get the following error in the Chrome console:

```
TypeError: $(...).select2 is not a function
```

It seems that jQuery doesn't have the Select2 plugin loaded. But if try to load a raw select2 without Ractive, I don't have the issue.

entry.js, which is working:
```javascript
require('jquery');
require('select2');

$('select').select2();
```

This one is not working:
```javascript
require('jquery');
require('select2');
var Ractive = require('ractive');
require('ractive-decorators-select2');

var app = new Ractive({
    el: '#content',
    template: require('../templates/form.ractive')
});
```

Thank you

**Comment by sandermarechal** [comment]
I have never worked with Browserify before. I think the issue may be caused by select2 being loaded after this decorator (`require` calls can be async IIRC).

I have attempted to fix this in the `browserify` branch. Can you test it for me?

https://github.com/Prezent/ractive-decorators-select2/tree/browserify

**Comment by syfonseq** [comment]
Thanks for your answer and your work.
I'll try your branch as soon as possible and I keep you up to date.

**Comment by syfonseq** [comment]
Your branch is perfectly working :)

Can you publish a new release on npm please?

**Comment by sandermarechal** [comment]
Great! Version 0.1.6 should be installable from npm now.
